name: Go CI
on:
  pull_request:
  push:
    branches: [main]
jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: 'stable'
      - name: Format
        run: |
          files=$(gofmt -l $(git ls-files '*.go'))
          if [ -n "$files" ]; then
            echo "Go files not formatted:" && echo "$files" && exit 1
          fi
      - name: Lint
        run: go vet ./...
      - name: Test
        run: go test ./...
