name: Go CI
on:
  pull_request:
  push:
    branches: [main]
jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: 'stable'
      - uses: golangci/golangci-lint-action@v4
        with:
          version: v2.1.6

      - name: Format
        run: |
          make fmt | tee fmt.log
          git diff --exit-code
      - name: Lint
        run: make lint
      - name: Test
        run: make test
      - name: Build
        run: make build
